### ISSUE TITLE
Кракозяблы в русском интерфейсе в v.7

### ISSUE THREAD

**Issue by keltstr** [abstractspoon/ToDoList_Downloads#1]
После обновления с v.6.9.6 на v.7 весь интерфейс стал в кракозяблах.
В дереве проекта и окне редактирования кирилица отображается нормально.
Переключился на ENG интерфейс (хорошо что иконка(шестеренка) и на первой вкладке сразу выпадающее меню с флагами, а то бы не нашел где изменить)
After update from v.6.9.6 to v.7 all interface (russian) has wrong charset view.

**Comment by Pierre-de-la-Verre** [comment]
Google translate:

After the upgrade to v.7 v.6.9.6 on the whole interface is in krakozyablah.
In the project tree and editing window displays Cyrillic normal.
ENG switched to the interface (well that the icon (gear) on the first tab, just drop down menu with flags, but it would not find where to change)

Hi keltstr
please consider the following points:

a) Please write in English. The number of Russian speaking people here in abstractspoon - Github is rather low.

b) For common discussions or question please you the forum at
http://www.codeproject.com/Articles/5371/ToDoList-An-effective-and-flexible-way-to-keep-on
Maybe there are more people with Russian language.

c) For issues to be solved please use "Todolist Issues"
https://github.com/abstractspoon/ToDoList_Issues
There is also an information how to report and how to document bugs and issues.

So please close this issue here.

**Comment by keltstr** [comment]
After update from v.6.9.6 to v.7 all interface (russian) has wrong charset view.

**Comment by Pierre-de-la-Verre** [comment]
Please download the package manually and copy the russian-file from download package to your translations-folder.

**Comment by TonyGravagno** [comment]
@keltstr can leave this open but if this isn't an issue with the Russian.zip dictionary I'll ask Dan to move it to Issues. If a manual update of a dictionary is required to avoid language issues, I'd like to add a note to the wiki. So is this a product issue or a usage issue?

**Comment by Pierre-de-la-Verre** [comment]
> So is this a product issue or a usage issue?
Since downloading from Github there are problems with file-format (UTF-8 with or without BOM), and this has impact on languages with "demands" on the char-set (e.g. German Umlaute). The BOM in Github was fixed by Dan some days ago - I don't know what the background of the current topic is ....

**Comment by keltstr** [comment]
Where can I download the package manually?

**Comment by Pierre-de-la-Verre** [comment]
Here, on the top under "Downloads":
http://www.codeproject.com/Articles/5371/ToDoList

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Issues#66

**Comment by abstractspoon** [comment]
This issue was moved to abstractspoon/ToDoList_Issues#67
